services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: admin@123
      DB_NAME: php_travel_express
    volumes:
      - .:/var/www/html

volumes:
  db_data:
